services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    # Create a named volume for app code
    volumes:
      - laravel_app:/var/www/html
    depends_on:
      - db
    networks:
      - laravel_net

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_classroom
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: laravel
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_net

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "61234:80"
    volumes:
      - laravel_app:/var/www/html:ro  # Share the same volume as the app container
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - app
    networks:
      - laravel_net

networks:
  laravel_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.91.0/24

volumes:
  dbdata:
    driver: local
  laravel_app:  # Define a named volume for the application code
    driver: local
